# Generated by Django 4.1.4 on 2022-12-17 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_account_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_phone',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
