# Generated by Django 4.1.4 on 2022-12-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_account',
            new_name='user',
        ),
    ]
