# Generated by Django 4.1.4 on 2022-12-17 15:53

import Online_shop.validators.input_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(2), Online_shop.validators.input_validators.validate_only_letters, Online_shop.validators.input_validators.validate_no_special_symbols_include]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=50),
        ),
    ]
