# Generated by Django 4.1.4 on 2023-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_likes_product_sales_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
